### PR TITLE
Add an API for plugins

### PR DESCRIPTION
**Pull request by Akul2010**
I have started work on the API with FastAPI, which seems to be faster than most of it's other competitors and easy to learn. This also doesn't require as much code. I'm not done yet, but I'm probably halfway done already. (FastAPI is very easy to use, I'm surprised.)

### CODE REVIEW

**Comment by Akul2010** [comment]
One thing that confuses me is how I will run the API. The run scripts will run an output similar to this: 
`INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)`
How would I automate running that in the browser?

**Comment by Akul2010** [comment]
One other potential problem I see with this is that if the API is hosted on another link, the plugins will be unable to access the speak and listen functions.

**Comment by aaronchantrill** [comment]
I was thinking you would build the individual components and have them served by a regular webserver like Apache or Nginx. That way adding new skills would be simply a matter of deploying the app, and it would make very little difference what language the plugins are written in. Uvicorn (which I have not worked with before) appears to be a webserver in its own right, like a Tomcat sort of thing. I have written web applications in Python as well as Perl and NodeJS before, and Restful applications aren't much different.

When the app wants to speak to the user (and possibly wait for a response), it would send a web request to a "talk" api also deployed as a web service. You would just need a list of endpoints that all the services would somehow have access to.

Rhasspy uses the mqtt protocol for this. I think this is because mqtt is used by home automation servers like "Home Assistant" and "OpenHAB".

**Comment by Akul2010** [comment]
I'm not sure I understand what you mean. Are you saying that each function would be its own kind of app, connected to each other with this repository?

**Comment by aaronchantrill** [comment]
Each function would be a RESTful web service. They would communicate with each other over http. That's what I was understanding. That way it doesn't matter what language an app is written in. It's fine to write the webserver itself in python, but I don't know how easy it is to serve non-python content from a python webserver like Flask or WSGI. It seems like you would still end up using subprocess to run the Perl or JS plugins.

**Comment by aaronchantrill** [comment]
I may just be confused about what you are trying to do exactly.

**Comment by Akul2010** [comment]
I will look into what you said about using the MQTT protocol (honestly I have never heard of it before). I was actually thinking that the plugins would access the functions through the webserver and then use them normally. I didn't think I would need to send something back because then the plugin code would just run normally on your device.

**Comment by Akul2010** [comment]
In other words, I mainly just wanted to give all the plugins access to the speak and listen functions. That's really it.

**Comment by Akul2010** [comment]
@aaronchantrill If you have the time, could you please implement your idea? I still don't completely understand it, but my implementation wasn't working very well on a Raspberry Pi, which is kind of the target machine I want it to run on. Of course, I still wan to run it on other platforms too, which it is working on. The whole thing already seems to crash on startup, and I suspect it is because of the FastAPI code.

**Comment by Akul2010** [comment]
I messed up a bit when testing, so I'll close this and copy everything from here into a new pull request.

**Pull request closed without merging**
