### PR TITLE
Updated create_plugins.md

### PR DESCRIPTION
**Pull request by aaronchantrill**
Updated create_plugins.md with the current instructions for creating plugins in Python, Perl and Javascript.

Also removed some debugging output lines from akulai.py.

### CODE REVIEW

**Comment by Akul2010** [comment]
All I need to do now is start working on the API so that the plugins can access the speak and listen functions.

**Comment by Akul2010** [comment]
I think we could make a RESTful API, where a GET request to the Speak endpoint with the text to be spoken as a parameter could trigger the Speak function, and a POST request to the Listen endpoint could return the text recognized from the audio input. What do you think?

**Comment by aaronchantrill** [comment]
@Akul2010 I think that makes a lot of sense. Write everything as web services with well-defined api's, then the application as a bit of glue to hold them together. I like that it also provides a way for skills to access resources like microphone and speakers and even other skills directly regardless of what language things are written in. And it will make horizontal scaling really easy if needed.

**Comment by Akul2010** [comment]
Perfect. I'll get to work with FastAPI because I'm not that proficient in Flask.

**Pull request merged**
