### PR TITLE
Plugin system overhaul

### PR DESCRIPTION
**Pull request by Akul2010**
I re-wrote the plugin system because it was so messy. Marking this as a draft PR until all other minor problems are fixed. I still need to update the docs and add some more features, like checking the plugin.info file.

### CODE REVIEW

**Comment by aaronchantrill** [comment]
Cool, thanks for working on this. I've set up a new dev environment in a virtual machine to work on this.

I had to install portaudio19-dev manually. I also modified the INSTALL to put the virtual python environment into a venv directory instead of directly into akulai (although I like the fact that it tells me it is in the akulai virtualenv if I put it directly into that directory) because putting it directly into the akulai directory cluttered it up with subdirectories.

Also, the README.md instructions at https://github.com/Akul-AI/akulai/blob/master-v2/README.md say to download and extract the model, rename it to vosk_model and put it in the akulai directory, but it should actually be put into a model directory which is in the akulai directory.

I also had to manually install libespeak-ng-libespeak1 to get pyttsx3 to work.

I'll send a pull request later.

**Comment by Akul2010** [comment]
Okay, thanks!

**Comment by Akul2010** [comment]
For the JavaScript plugins. we have `js2py`. I have been researching and found a module called `perlmodule` which works very similar to `js2py`, but for Perl. Here is the article I found out from: https://metacpan.org/release/GAAS/pyperl-1.0/view/perlmodule.pod

**Comment by aaronchantrill** [comment]
It seems like using subprocess to call either node or perl to interpret the scripts will probably work better than using a parser built into python. I assume people trying to write plugins in perl or nodejs will be doing so because they are familiar with those languages, and worry they might have problems with the python interpreters not working quite they way they expect.

The main problem I think you need to start defining is how to deal with input and output. You could start with just passing the utterance as a parameter like `node myplugin/main.js "what time is it"` and returning the response as a simple string like "the time right now is ten fifteen a.m.", although I would encourage to pass json strings since you will probably want to add information as you continue working (for instance, you might want to pass the identity of the person speaking, and you might want to return an emotional state in addition to the text).

Passing a json string like `node myplugin/main.js "{text: \"what time is it\"}` and retrieving something like "{response: \"It is ten fifteen a.m.\"}" would provide more flexibility for future development, but obviously has the potential to introduce injection vulnerabilities. That's another reason running the skills as webservices might be nice, although it would make setup more complex.

Thanks!

**Comment by aaronchantrill** [comment]
Sorry, I didn't realize you were waiting for my review. I'll pull down a copy tomorrow review it.

**Comment by Akul2010** [comment]
Do you suggest making an API for the plugins? I have been sick for a while, I couldn't really do much either.

**Review by aaronchantrill — APPROVED** [review]
@Akul2010 yes, I think you should think about an api for passing information into and out of the plugins, as well as a way of establishing activation words without having to call each of the plugins.

I notice that you are trying to call akulAI.speak from a the js and perl plugins, which is not going to work. They have no way of knowing the akulAI object exists or of accessing it even if you were able to pass a reference to it.

I did the easiest route to passing information into and out of a subprocess. I'm passing the incoming command as a parameter. I'm using double quotes to delimit the command, since double quotes are unlikely to appear in an utterance while single quotes may show up as apostrophes. I am receiving the text to speak back from stdout (print() from perl, console.write() from js). This will require re-writing all the plugins. My suggestion is to use JSON strings to pass information into and back out of the plugin. That will make it easier to add additional bits of information later (like the identity of the speaker or any values parsed out of the utterance on the front end, etc).

The weather plugin is using a broken library and needs to be re-written with something more current to actually function. The Naomi project has plugins for both the Hong Kong based World Weather Information Service which provides weather forecasts for select cities around the world, and the NWS which provides more targeted weather forecasts for cities in the United States. They both use RestFull web interfaces and should be easy to implement in Python, Javascript or Perl.

Not having access directly to the speaker and microphone access methods becomes an issue when you are scripting a conversation. For example, see the "Joke" plugin for Naomi which tells a knock knock joke and waits for the correct responses. This is also used when you are writing an interface for a web service that require parameters that the user didn't supply in the initial query. I.e.: "Book me a flight to Paris" with followups "Is that Paris France or Paris Texas?" "When would you like to go to Paris?" "Do you want a one way ticket or round trip?" etc. but I'm sure there are ways around that.

There are a couple of ways to really improve the performance of AkulAI. One is to use a voice activity detector rather than trying to process of every block of audio. I'd like to work on that next. The other would be to use an intent parser rather than calling every plugin in turn to see how each wants to handle the utterance. It seems like the easiest thing would be to add some sort of grammar file to each plugin defining the sorts of utterances it could respond to. It seems like it would make sense to use SRGS since it is a web standard. The problems with that being that python does not currently appear to have an SRGS parser, and the format is not particularly easy to write.

As far as I can tell, properly written plugins should now work.

**Comment by Akul2010** [comment]
Could you please update the docs too? I am not exactly sure how you are imagining the plugins would currently look like (after these fixes). I have been thinking about which intent parser to use. My original thought was Adapt or Padatious from Mycroft, but as far as I know, they are Linux-based only and require a lot of computing power. I think I might just roll my own, a very simple one.

**Comment by aaronchantrill** [comment]
Which docs exactly? Are you referring to akulai/docs/create_plugins.md? I'm happy to update that document, but please let me know more specifically you want. As far as intent parsers - padatious is a pain in the rear to install. I think Adapt is written in Python. You can just `pip install adapt-parser`. I think it is available for Windows.

The syntax for Naomi's intent parser was originally created based on what would be easy to integrate with adapt and padatious. I wish I had realized at the time was that slots need both a name and a type. So you could have things like:

What is {numerator}&lt;number&gt; divided by {divisor}&lt;number&gt;

instead of what we currently have which is:

What is {number} divided by {number}

I do think you should write your own intent parser. It really doesn't have to be fancy to work well, and I'm sure you'll start thinking of new ideas as soon as you start using it. Naomi's default intent parser is pretty simple. It's just based on edit distance with the words weighted by frequency.

**Comment by Akul2010** [comment]
I meant the create-plugins.md doc, can you please change the example plugins the way you think is necessary? I can do everything else from there. I will also look into how I can make an intent parser for this.

**Pull request merged**
